### ISSUE TITLE
Create official seco-hfst release and publish on Maven central

### ISSUE THREAD

**Issue by marko-asplund** [jiemakel/seco-hfst#2]
An official release published on Maven central would make it much easier for developers to use seco-hfst.

**Comment by jiemakel** [comment]
It's now finally there as version 1.1 (https://repo1.maven.org/maven2/fi/seco/hfst/1.1/)

**Comment by marko-asplund** [comment]
brilliant, thanks! :thumbsup: 

not yet visible through search.maven.org, but this may be due to an indexing delay.

**Comment by marko-asplund** [comment]
now it appears in search, as well:

http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22hfst%22
